import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { ClerkProvider } from "@clerk/nextjs";

import { Inter } from "next/font/google";
import { TopNav } from "./_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "sonner";
import { CSPostHogProvider } from "./_analytics/provider";
import { BackgroundBeams } from "~/components/ui/background-beams";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "ProSafeX",
  description: "Generated by shreyansh",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <CSPostHogProvider>
        <>
          <html lang="en">
            <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
            <body className={`font-sans ${inter.variable}`}>
                <div className="grid h-screen grid-rows-[auto_1fr]">
                <BackgroundBeams />
                  <TopNav />
                  {children}
                </div>
            </body>
          </html>
        </>
      </CSPostHogProvider>
    </ClerkProvider>
  );
}
